# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'get_latest_by': 'modified', 'ordering': ['-modified']},
        ),
    ]
