# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:40
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('labeled', models.BooleanField()),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'corpus',
                'db_table': 'corpora',
                'get_latest_by': 'created',
                'verbose_name_plural': 'corpora',
            },
        ),
        migrations.CreateModel(
            name='LabeledDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Corpus')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Document')),
                ('label', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.Label')),
            ],
            options={
                'db_table': 'corpora_documents',
            },
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'get_latest_by': 'modified', 'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='corpus',
            name='documents',
            field=models.ManyToManyField(related_name='corpora', through='corpus.LabeledDocument', to='corpus.Document'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to=settings.AUTH_USER_MODEL),
        ),
    ]
