# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_corpus_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='labeled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='labeleddocument',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='corpus.Corpus'),
        ),
        migrations.AlterField(
            model_name='labeleddocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.Document'),
        ),
    ]
