# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20160718_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('document', 'user')]),
        ),
    ]
