# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20160821_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
