# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20160718_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.CharField(blank=True, default=None, editable=False, max_length=44, null=True),
        ),
    ]
