# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:47
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20160718_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
