# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_corpus'),
        ('arbiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimator',
            name='corpus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.Corpus'),
        ),
    ]
